# Generated by Django 3.2.3 on 2021-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='name',
            field=models.CharField(default='files', max_length=200),
        ),
    ]
